
package finalproject;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.*;
import javax.swing.*;

public class JFrame_Edit_List extends javax.swing.JFrame {

    Item_List iList = new Item_List();
    int position = 0; // current position of Item
    int numItems = 0; // number of Items in the list
    public JFrame_Edit_List() {
        initComponents();
        deserializeItem_List();
        if(!iList.isEmpty()){
           populate_TextBoxes(iList.get(position),position+1); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_Rating = new javax.swing.JComboBox<>();
        jButton_First = new javax.swing.JButton();
        jButton_Prev = new javax.swing.JButton();
        jButton_Next = new javax.swing.JButton();
        jButton_Last = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Sort = new javax.swing.JButton();
        jTextField_Title = new javax.swing.JTextField();
        jTextField_Time = new javax.swing.JTextField();
        jTextField_Artist = new javax.swing.JTextField();
        jTextField_Number_of_Tracks = new javax.swing.JTextField();
        jTextField_Search = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Title");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Playing Time");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Artist");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Number of Tracks");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ratings");

        jComboBox_Rating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Good", "Very good", "Bad" }));
        jComboBox_Rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_RatingActionPerformed(evt);
            }
        });

        jButton_First.setText("|<");
        jButton_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FirstActionPerformed(evt);
            }
        });

        jButton_Prev.setText("<<");
        jButton_Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PrevActionPerformed(evt);
            }
        });

        jButton_Next.setText(">>");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jButton_Last.setText(">|");
        jButton_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LastActionPerformed(evt);
            }
        });

        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Sort.setText("Sort");
        jButton_Sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SortActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Data Manipulation Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_First, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Update)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox_Rating, 0, 138, Short.MAX_VALUE)
                                .addGap(189, 189, 189))
                            .addComponent(jTextField_Number_of_Tracks)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Delete))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton_Sort)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField_Title)
                            .addComponent(jTextField_Time)
                            .addComponent(jTextField_Artist))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Artist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Number_of_Tracks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Rating, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_First)
                            .addComponent(jButton_Prev)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Next)
                            .addComponent(jButton_Last))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Add)
                        .addComponent(jButton_Update))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Delete)
                        .addComponent(jButton_Sort)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  //Deserialize single Item List
public void deserializeItem_List(){
    
    try{
      
     FileInputStream fin = new FileInputStream("Item.ser");
     ObjectInputStream ois = new ObjectInputStream(fin);
           
     iList = (Item_List) ois.readObject();
     numItems = iList.num_Items();
     ois.close();
    
     //return item;
     
    }
    catch(Exception e){
     JOptionPane.showMessageDialog(null,e.getMessage());
     
    } 
   }

public void serializeItem_List(){
    
    try{
      
      FileOutputStream fout = new FileOutputStream("Item.ser");
      ObjectOutputStream oos = new ObjectOutputStream(fout);   
      oos.writeObject(iList);
      oos.close();
      //JOptionPane.showMessageDialog(null,"Successfully saved");
      
    }
    catch(Exception e){
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
  }

private Item create_Item(){
        // Number Format try korte hobe
        if(this.jTextField_Title.getText().isEmpty()||this.jTextField_Time.getText().isEmpty() || this.jTextField_Artist.getText().isEmpty() || this.jTextField_Number_of_Tracks.getText().isEmpty() || this.jComboBox_Rating.getSelectedItem().toString().contentEquals("None"))
            return null;
        String Title = this.jTextField_Title.getText().trim();
        String Time_Text = this.jTextField_Time.getText().trim();
        String Artist = this.jTextField_Artist.getText().trim();
        String Numoftracks_Text = this.jTextField_Number_of_Tracks.getText().trim();
        String Rating = this.jComboBox_Rating.getSelectedItem().toString();
        try{
            int time = Integer.parseInt(Time_Text);
            int numoftracks = Integer.parseInt(Numoftracks_Text);
            return new Item(Title,time,Artist,numoftracks,Rating);
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please input an integer for Time");
            return null;
        }
    }
    private void populate_TextBoxes(Item item, int pos){
        this.jTextField_Title.setText(item.getTitle());
        this.jTextField_Time.setText(Integer.toString(item.getPlayingTime()));
        this.jTextField_Search.setText(pos+"/"+numItems);
        this.jTextField_Artist.setText(item.getArtist());
        this.jTextField_Number_of_Tracks.setText(Integer.toString(item.getnumoftracks()));
        this.jComboBox_Rating.setSelectedItem(item.getRating());
    }
    private void Clear_TextBoxes(){
        this.jTextField_Title.setText("");
        this.jTextField_Time.setText("");
        this.jTextField_Search.setText("");
        this.jTextField_Artist.setText("");
        this.jTextField_Number_of_Tracks.setText("");
    }
  
    private void jButton_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FirstActionPerformed
                position=0;
        populate_TextBoxes(iList.get(position),position+1);
    }//GEN-LAST:event_jButton_FirstActionPerformed

    private void jButton_PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PrevActionPerformed
        if(position>0)
            position--;
        populate_TextBoxes(iList.get(position),position+1);
    }//GEN-LAST:event_jButton_PrevActionPerformed

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        if(position<(iList.num_Items()-1))
            position++;
        populate_TextBoxes(iList.get(position),position+1);
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
                Item newItem = create_Item();
        if(newItem==null)
                JOptionPane.showMessageDialog(null,"Item is not properly created");
        if(iList.Contains(newItem))
                JOptionPane.showMessageDialog(null,"Item already exists");
        if(!(newItem==null) && (!iList.Contains(newItem))){
            iList.addItem(newItem);
            numItems++;
            position = numItems-1; // set position to last Item
            serializeItem_List();
            populate_TextBoxes(iList.get(position),position+1);
        }
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
          Item newItem = create_Item();
        if(newItem==null)
                JOptionPane.showMessageDialog(null,"Item is not properly created");
        if(iList.Contains(newItem))
                JOptionPane.showMessageDialog(null,"Item already exists");
        if(!(newItem==null) && (!iList.Contains(newItem)))
            iList.updateItem(position,newItem);
        if(!iList.isEmpty()){
            serializeItem_List();
            //populate_TextBoxes(iList.get(position),position+1);
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
                if(!iList.isEmpty()){
            iList.deleteItem(position);
            serializeItem_List();
            numItems--;
            if(position == numItems)
               position-- ;
            if(iList.isEmpty())
                Clear_TextBoxes();
            else
                populate_TextBoxes(iList.get(position),position+1); 
        }
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_SortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SortActionPerformed
               if(!iList.isEmpty()){
            iList.Sort();
            serializeItem_List();
            position = 0;
            populate_TextBoxes(iList.get(position),position+1);
        }
    }//GEN-LAST:event_jButton_SortActionPerformed

    private void jButton_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LastActionPerformed
        position=iList.num_Items()-1;
        populate_TextBoxes(iList.get(position),position+1);
    }//GEN-LAST:event_jButton_LastActionPerformed

    private void jComboBox_RatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_RatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_RatingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Edit_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Edit_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Edit_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Edit_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Edit_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_First;
    private javax.swing.JButton jButton_Last;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JButton jButton_Prev;
    private javax.swing.JButton jButton_Sort;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JComboBox<String> jComboBox_Rating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField_Artist;
    private javax.swing.JTextField jTextField_Number_of_Tracks;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_Time;
    private javax.swing.JTextField jTextField_Title;
    // End of variables declaration//GEN-END:variables
}
